GET http://localhost:5000/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.VGVzdFVzZXI.vAQOd6sU8SL5n1C3M3tlDKcoZtGI3EY0cNe0WhsaywY
###
GET http://localhost:5000/todos/
###
POST http://localhost:5000/todos
Content-Type: application/json

{
    "content": "Finish these routes"
}
###
DELETE http://localhost:5000/todos/
###
PATCH http://localhost:5000/todos/68d04dea3982b9ad3ca51e69
Content-Type: application/json

{
    "isDone": "true"
}

###
GET http://localhost:5000/users


###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "User@test.com",
    "password": "TestPassword123"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "User@test.com",
    "password": "TestPassword123"
}

###
POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDUzM2FhZDYxYTYwZjcxNTJhODFkNyIsImVtYWlsIjoidXNlckB0ZXN0LmNvbSIsImp0aSI6ImVmMmE3YTMzLWQ4MmEtNDU1OC05M2IzLThlMWU1NTE4YTdhYSIsImlhdCI6MTc1ODgwMzE0NCwiZXhwIjoxNzU5NDA3OTQ0fQ.jWrFJbR9PpxeZxx0NY2_Lqi9qPvNPquMMhV11TlVIUc"
}